version: 2.1
jobs:
  build:
    docker:
      - image: mgs4ff/persistence-api:latest
        environment:
          SQLALCHEMY_DATABASE_URI:postgresql: //adminuser:NvjJHj3M2Rpt50F6QQFL@receipt-ocr-db.cluster-cwvxj0zotizn.us-east-1.rds.amazonaws.com:5432/receipt-ocr
          SQLALCHEMY_TRACK_MODIFICATIONS: False
          CONNECTION_STRING: host=receipt-ocr-db.cluster-cwvxj0zotizn.us-east-1.rds.amazonaws.com dbname=receipt-ocr user=adminuser password=NvjJHj3M2Rpt50F6QQFL
    steps:
      - checkout
